name = "QXGraphDecompositions"
uuid = "b15f1ded-d19a-4aca-a940-1991fcfc7750"
authors = ["QuantEx team"]
version = "0.2.1"

[deps]
FlowCutterPACE17_jll = "008204e2-cd5c-5c6d-9360-d31f32b5f6c2"
LightGraphs = "093fc24a-ae57-5d10-9952-331d41423f4d"

[compat]
julia = "1.5, 1.6"
LightGraphs = "1.3"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
